[package]
name = "fea-rs"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
description = "Tools for working with Adobe OpenType Feature files."
repository = "https://github.com/cmyr/fea-rs"
categories = ["parsing", "text-processing"]
keywords = ["fonts", "opentype"]
readme = "README.md"
edition = "2018"
default-run = "parse_test"
exclude = ["test-data"]

[dependencies]
ansi_term = "0.12.1"
smol_str = "0.1.18"
xflags = "0.2.3"
norad = "0.5" # just for use in sample binaries/debugging, remove eventually
fonttools = { path="../../extern/fonttools-rs", features = ["rayon"] }

[dev-dependencies]
diff = "0.1.12"

