[package]
name = "fea-rs"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
description = "Tools for working with Adobe OpenType Feature files."
repository = "https://github.com/cmyr/fea-rs"
categories = ["parsing", "text-processing"]
keywords = ["fonts", "opentype"]
readme = "README.md"
edition = "2018"
default-run = "parse_test"
exclude = ["test-data"]

[dependencies]
ansi_term = "0.12.1"
smol_str = "0.1.18"
norad = "0.5" # just for use in sample binaries/debugging, remove eventually
font-types = { version = "0.0.2", path = "../../fontations/font-types" }
write-fonts = { version = "0.0.2", path = "../../fontations/write-fonts" }
read-fonts = { version = "0.0.2", path = "../../fontations/read-fonts" }
xflags = "0.2.3"
diff = { version = "0.1.12", optional = true }
rayon = { version = "1.5", optional = true }
chrono = "0.4.3"

[features]
test = ["diff", "rayon"]

[dev-dependencies]
diff = "0.1.12"
rayon = "1.5"
criterion = "0.3"

[[bench]]
name = "parsing"
harness = false

[[bin]]
name = "fea-rs"
path = "src/bin/compile.rs"

# this is an example so it can use dev-dependencies
[[bin]]
name = "ttx_test"
required-features = ["test"]
